### ISSUE TITLE
GTK 3.0 development libraries are required for Linux development.

### ISSUE THREAD

**Issue by labulakalia** [flutter-actions/setup-flutter#14]
```
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
```

**Comment by socheatsok78** [comment]
You can install additional software on GitHub-hosted runners as a part of your workflow, here an example.

```yml
name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install GTK 3.0 development libraries
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev
```

You can read more about it [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners)
