### ISSUE TITLE
Flutter version: latest support

### ISSUE THREAD

**Issue by hurelhuyag** [flutter-actions/setup-flutter#5]
Currently, I am using config like this. Occasionally, This requires me to update the version property.
```yaml
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.13.1
```
What if we have `version:latest` support? Is this possible?

```yaml
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: latest
```
