### ISSUE TITLE
Cannot publish in such env.

### ISSUE THREAD

**Issue by aprosail** [flutter-actions/setup-flutter#7]
I've wrote a script based on such Flutter SDK env setup in order to publish a Flutter package onto pub.dev. Publishing from GitHub Actions [requires OIDC](https://dart.dev/tools/pub/automated-publishing), but once using this action, even if `permissions: {id-token: write}` is enabled, it cannot authentic with OIDC and the publishing process can never finish.

Here's my `publish.yaml` file inside `.github/workflows` folder:

```yaml
name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  # https://dart.dev/tools/pub/automated-publishing
  publish:
    runs-on: ubuntu-latest
    permissions: {id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
      - run: flutter pub get
      - run: flutter pub publish --dry-run
      - run: flutter pub publish --force
```

**Comment by aprosail** [comment]
I've found a solution, but it's a little bit waste computational resources: add a line to setup Dart environment using [the official Dart setup action](https://github.com/dart-lang/setup-dart), and it can publish normally. Just like the following code:

```yaml
name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  # https://dart.dev/tools/pub/automated-publishing
  publish:
    runs-on: ubuntu-latest
    permissions: {id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: flutter-actions/setup-flutter@v3
      - run: flutter pub get
      - run: flutter pub publish --dry-run
      - run: flutter pub publish --force
```

But this workflow will also setup a Dart environment, which is repeated, as the Flutter SDK includes a Dart SDK. So it's still recommended to fix something about OIDC in this action repo.
